from app.curriculum.python_core import _q


PYTHON_DEEP_TOPICS = [
    {
        "key": "mutability_copying",
        "title_en": "Mutability and Copying",
        "title_ru": "Изменяемость и копирование",
        "description_en": "How shared references, shallow copies and immutable values behave.",
        "description_ru": "Общие ссылки, поверхностные копии и неизменяемые значения.",
        "questions": [
            _q("beginner", "Which built-in collection is mutable?", "Какая встроенная коллекция изменяема?", "list", ["tuple", "str", "frozenset"]),
            _q("beginner", "If b = a for a list, what do a and b initially reference?", "Если для списка выполнить b = a, на что сначала указывают a и b?", "The same list", ["Two automatic copies", "Two tuples", "Nothing"]),
            _q("intermediate", "Which expression makes a shallow copy of a list named items?", "Какое выражение создаёт поверхностную копию списка items?", "items.copy()", ["items = copy", "copy(items) without importing anything", "items.clone()"]),
            _q("intermediate", "Why can changing a nested list affect a shallow copy?", "Почему изменение вложенного списка может повлиять на поверхностную копию?", "Nested objects are still shared", ["Python deletes the copy", "Lists are always immutable", "copy() sorts the data"]),
            _q("advanced", "Which module provides deepcopy()?", "Какой модуль содержит deepcopy()?", "copy", ["math", "json", "types"]),
        ],
    },
    {
        "key": "unpacking_comprehensions",
        "title_en": "Unpacking and Comprehensions",
        "title_ru": "Распаковка и включения",
        "description_en": "Compactly unpacking values and building collections from loops.",
        "description_ru": "Компактная распаковка значений и создание коллекций из циклов.",
        "questions": [
            _q("beginner", "After x, y = (4, 9), what is x?", "После x, y = (4, 9) чему равен x?", "4", ["9", "(4, 9)", "x"]),
            _q("beginner", "What does a list comprehension create?", "Что создаёт списковое включение?", "A new list", ["A class", "A file", "An exception"]),
            _q("intermediate", "What is [n for n in range(5) if n % 2 == 0]?", "Чему равно [n for n in range(5) if n % 2 == 0]?", "[0, 2, 4]", ["[1, 3, 5]", "[2, 4]", "[0, 1, 2, 3, 4]"]),
            _q("intermediate", "What does *rest collect in first, *rest = [1, 2, 3]?", "Что собирает *rest в first, *rest = [1, 2, 3]?", "[2, 3]", ["1", "[1, 2]", "3"]),
            _q("advanced", "Which expression creates a dictionary of n to n*n?", "Какое выражение создаёт словарь n и n*n?", "{n: n*n for n in range(3)}", ["[n: n*n for n in range(3)]", "{n*n for n in range(3)}", "dict(n*n)"]),
        ],
    },
    {
        "key": "builtins",
        "title_en": "Useful Built-in Functions",
        "title_ru": "Полезные встроенные функции",
        "description_en": "Using enumerate, zip, sorted, any, all, min, max and sum.",
        "description_ru": "Использование enumerate, zip, sorted, any, all, min, max и sum.",
        "questions": [
            _q("beginner", "Which function adds all numbers in a collection?", "Какая функция складывает все числа коллекции?", "sum()", ["all()", "zip()", "type()"]),
            _q("beginner", "Which function finds the largest value?", "Какая функция находит наибольшее значение?", "max()", ["min()", "top()", "large()"]),
            _q("intermediate", "What does enumerate(items) provide during a loop?", "Что даёт enumerate(items) во время цикла?", "An index and an item", ["Two copies of each item", "Only sorted items", "A dictionary"]),
            _q("intermediate", "What does zip(names, scores) combine?", "Что объединяет zip(names, scores)?", "Items from matching positions", ["Only the longest list", "All possible pairs", "Two strings"]),
            _q("advanced", "When is all([True, True, False]) true?", "Когда all([True, True, False]) истинно?", "It is not true because one value is False", ["Always", "Only because the first value is True", "When the list is sorted"]),
        ],
    },
    {
        "key": "function_design",
        "title_en": "Function Design and Closures",
        "title_ru": "Проектирование функций и замыкания",
        "description_en": "Default arguments, keyword-only values, closures and pure functions.",
        "description_ru": "Аргументы по умолчанию, именованные аргументы, замыкания и чистые функции.",
        "questions": [
            _q("beginner", "What should one well-designed function usually do?", "Что обычно должна делать хорошо спроектированная функция?", "One clear job", ["Every task in the program", "Only print text", "Create a global variable"]),
            _q("beginner", "Why are return values useful?", "Почему полезны возвращаемые значения?", "Other code can reuse the result", ["They close Python", "They make every variable global", "They remove parameters"]),
            _q("intermediate", "Why should a list usually not be a mutable default argument?", "Почему список обычно не стоит использовать как изменяемый аргумент по умолчанию?", "The same list can be reused across calls", ["Lists cannot store values", "Defaults run after return", "Python converts it to a tuple"]),
            _q("intermediate", "What is a closure?", "Что такое замыкание?", "A function that remembers values from an outer scope", ["A closed file", "A loop with break", "A private class"]),
            _q("advanced", "What is a pure function?", "Что такое чистая функция?", "A function without hidden side effects for the same inputs", ["A function with no parameters", "A function that only prints", "A function inside a class"]),
        ],
    },
    {
        "key": "advanced_oop",
        "title_en": "Advanced Object-Oriented Python",
        "title_ru": "Продвинутое объектно-ориентированное программирование",
        "description_en": "Properties, class methods, static methods and special methods.",
        "description_ru": "Свойства, методы класса, статические и специальные методы.",
        "questions": [
            _q("beginner", "Which special method creates a readable string for users?", "Какой специальный метод создаёт понятную строку для пользователя?", "__str__", ["__len__", "__add__", "__enter__"]),
            _q("beginner", "What does @property allow?", "Что позволяет @property?", "Method logic accessed like an attribute", ["A class to become a list", "Every method to be static", "Imports inside objects"]),
            _q("intermediate", "What is the first parameter of a class method usually called?", "Как обычно называется первый параметр метода класса?", "cls", ["self", "this", "class"]),
            _q("intermediate", "When is @staticmethod suitable?", "Когда подходит @staticmethod?", "The behavior belongs to the class but needs no instance or class data", ["The method must change self", "The method creates every object", "The method must be recursive"]),
            _q("advanced", "Which special method can define len(obj)?", "Какой специальный метод может определить len(obj)?", "__len__", ["__size__", "__count__", "__str__"]),
        ],
    },
    {
        "key": "dataclasses_typing",
        "title_en": "Dataclasses and Type Hints",
        "title_ru": "Dataclass и подсказки типов",
        "description_en": "Describing data objects and documenting expected value types.",
        "description_ru": "Описание объектов данных и ожидаемых типов значений.",
        "questions": [
            _q("beginner", "What do type hints mainly communicate?", "Что в основном сообщают подсказки типов?", "Expected value types", ["Guaranteed runtime speed", "File permissions", "Loop counts"]),
            _q("beginner", "Do standard Python type hints normally block every wrong type at runtime?", "Обычные подсказки типов всегда блокируют неверный тип во время выполнения?", "No", ["Yes", "Only for strings", "Only in loops"]),
            _q("intermediate", "Which decorator creates a data-focused class with generated methods?", "Какой декоратор создаёт класс данных с готовыми методами?", "@dataclass", ["@property", "@staticmethod", "@data"]),
            _q("intermediate", "What does list[str] describe?", "Что описывает list[str]?", "A list expected to contain strings", ["A string converted to a list automatically", "A list named str", "A fixed-length tuple"]),
            _q("advanced", "Which tool commonly checks type hints without running the program?", "Какой инструмент обычно проверяет подсказки типов без запуска программы?", "A static type checker", ["The print function", "A web browser", "The math module"]),
        ],
    },
    {
        "key": "paths_context",
        "title_en": "Paths and Context Managers",
        "title_ru": "Пути и контекстные менеджеры",
        "description_en": "Using pathlib and safely managing files or other resources.",
        "description_ru": "Использование pathlib и безопасное управление файлами и ресурсами.",
        "questions": [
            _q("beginner", "Which modern module works with filesystem paths?", "Какой современный модуль работает с путями файловой системы?", "pathlib", ["random", "decimal", "typing"]),
            _q("beginner", "What keyword starts a context manager block?", "Какое слово начинает блок контекстного менеджера?", "with", ["using", "context", "open"]),
            _q("intermediate", "Why is Path('folder') / 'file.txt' useful?", "Почему удобно Path('folder') / 'file.txt'?", "It joins path parts clearly", ["It divides file contents", "It deletes the folder", "It opens the file automatically"]),
            _q("intermediate", "What does a context manager guarantee for a file?", "Что контекстный менеджер гарантирует для файла?", "Cleanup such as closing it", ["The file has no errors", "The file is always empty", "The filename is changed"]),
            _q("advanced", "Which methods define a custom context manager class?", "Какие методы определяют собственный класс контекстного менеджера?", "__enter__ and __exit__", ["__start__ and __stop__", "__open__ and __close__", "__init__ and __str__"]),
        ],
    },
    {
        "key": "testing_debugging",
        "title_en": "Testing and Debugging",
        "title_ru": "Тестирование и отладка",
        "description_en": "Assertions, unit tests, tracebacks and systematic debugging.",
        "description_ru": "Утверждения, модульные тесты, traceback и системная отладка.",
        "questions": [
            _q("beginner", "What is a test meant to check?", "Что должен проверять тест?", "Whether code behaves as expected", ["Whether the screen is bright", "Whether Python is installed twice", "Whether variables have long names"]),
            _q("beginner", "What information does a traceback provide?", "Какую информацию даёт traceback?", "Where and how an error happened", ["Only the final answer", "A list of installed games", "The computer password"]),
            _q("intermediate", "What happens when assert condition fails?", "Что происходит, если условие assert ложно?", "AssertionError is raised", ["The condition becomes true", "Python silently fixes it", "A file is created"]),
            _q("intermediate", "Why should tests include edge cases?", "Почему тесты должны включать граничные случаи?", "Bugs often appear at unusual limits", ["Edge cases always run faster", "They replace normal cases", "They remove exceptions"]),
            _q("advanced", "What makes a good unit test independent?", "Что делает хороший модульный тест независимым?", "It does not depend on another test running first", ["It uses no functions", "It prints every variable", "It must connect to the internet"]),
        ],
    },
    {
        "key": "algorithms_complexity",
        "title_en": "Algorithms and Complexity",
        "title_ru": "Алгоритмы и сложность",
        "description_en": "Breaking down problems, searching, sorting and estimating work.",
        "description_ru": "Разбиение задач, поиск, сортировка и оценка количества работы.",
        "questions": [
            _q("beginner", "What is an algorithm?", "Что такое алгоритм?", "A step-by-step solution to a problem", ["A Python color theme", "A single variable", "A file extension"]),
            _q("beginner", "What should happen before writing a complex program?", "Что стоит сделать перед написанием сложной программы?", "Break the problem into smaller steps", ["Add many global variables", "Avoid examples", "Write random loops"]),
            _q("intermediate", "What does linear search do?", "Что делает линейный поиск?", "Checks items one by one", ["Always checks the middle item", "Sorts without comparisons", "Uses a database"]),
            _q("intermediate", "What must usually be true before binary search?", "Что обычно должно быть верно перед бинарным поиском?", "The data is sorted", ["The data contains strings only", "The list is empty", "The values are random"]),
            _q("advanced", "What does O(n) commonly mean?", "Что обычно означает O(n)?", "Work grows roughly with the number of items", ["The program takes exactly n seconds", "No work is required", "The result is always a number"]),
        ],
    },
    {
        "key": "async_concurrency",
        "title_en": "Async Programming Basics",
        "title_ru": "Основы асинхронного программирования",
        "description_en": "Coroutines, await and handling waiting tasks efficiently.",
        "description_ru": "Корутины, await и эффективная работа с задачами ожидания.",
        "questions": [
            _q("beginner", "Which keywords define an asynchronous function?", "Какие слова определяют асинхронную функцию?", "async def", ["await def", "async function", "parallel def"]),
            _q("beginner", "What kind of work benefits most from async programming?", "Какая работа чаще всего выигрывает от async?", "Tasks that spend time waiting for input or network data", ["Simple addition only", "Renaming variables", "Writing comments"]),
            _q("intermediate", "What does await do?", "Что делает await?", "Pauses the coroutine until an awaitable is ready", ["Stops the whole computer", "Creates a class", "Converts data to JSON"]),
            _q("intermediate", "Can await normally be used directly inside a regular def function?", "Можно ли обычно использовать await прямо внутри обычной функции def?", "No", ["Yes, anywhere", "Only in a list", "Only after print"]),
            _q("advanced", "What is the event loop responsible for?", "За что отвечает цикл событий?", "Scheduling and resuming asynchronous tasks", ["Compiling CSS", "Creating database tables automatically", "Changing type hints"]),
        ],
    },
]
