SOURCE_URL = "https://www.w3schools.com/python/"
COURSE_TITLE_EN = "Python"
COURSE_TITLE_RU = "Python"

OPTION_TRANSLATIONS_RU = {
    "Indentation": "Отступы",
    "Curly braces only": "Только фигурные скобки",
    "Semicolons": "Точки с запятой",
    "Quotation marks": "Кавычки",
    "A string": "Строка",
    "A boolean": "Логическое значение",
    "Nothing": "Ничего",
    "Always an integer": "Всегда целое число",
    "The integer 12": "Целое число 12",
    "The text '12'": "Текст '12'",
    "An error": "Ошибка",
    "True and False": "True и False",
    "Yes and No": "Да и нет",
    "On and Off": "Вкл. и выкл.",
    "Duplicate values": "Повторяющиеся значения",
    "All numbers": "Все числа",
    "All strings": "Все строки",
    "The first value": "Первое значение",
    "Key-value pairs": "Пары ключ-значение",
    "Rows and columns": "Строки и столбцы",
    "Unique values only": "Только уникальные значения",
    "Its condition": "Его условие",
    "A file": "Файл",
    "A comment": "Комментарий",
    "A function name": "Имя функции",
    "It performs no action": "Не выполняет никаких действий",
    "It stops Python": "Останавливает Python",
    "It repeats the block": "Повторяет блок",
    "It prints pass": "Выводит pass",
    "A name in a function definition": "Имя в определении функции",
    "The final printed value": "Последнее выведенное значение",
    "A Python file": "Файл Python",
    "A loop condition": "Условие цикла",
    "Local": "Локальная",
    "Global": "Глобальная",
    "Imported": "Импортированная",
    "Constant": "Константа",
    "Extra positional arguments": "Дополнительные позиционные аргументы",
    "Extra keyword arguments": "Дополнительные именованные аргументы",
    "Only keyword arguments": "Только именованные аргументы",
    "Only numbers": "Только числа",
    "Errors": "Ошибки",
    "Modules": "Модули",
    "Loop values": "Значения цикла",
    "Return statements": "Инструкции return",
    "A function calling itself": "Функция вызывает сама себя",
    "A list sorting itself": "Список сортирует сам себя",
    "A variable changing type": "Переменная меняет тип",
    "A module import": "Импорт модуля",
    "To stop the repeated calls": "Чтобы остановить повторные вызовы",
    "To print every result": "Чтобы вывести каждый результат",
    "To create a class": "Чтобы создать класс",
    "To import math": "Чтобы импортировать math",
    "They produce values lazily": "Они создают значения по мере необходимости",
    "They always sort values": "Они всегда сортируют значения",
    "They replace every class": "Они заменяют все классы",
    "They disable loops": "Они отключают циклы",
    "Installing Python packages": "Установка пакетов Python",
    "Writing comments": "Написание комментариев",
    "Creating loops": "Создание циклов",
    "Drawing windows": "Рисование окон",
    "To isolate project dependencies": "Чтобы изолировать зависимости проекта",
    "To speed up every loop": "Чтобы ускорить каждый цикл",
    "To replace Python": "Чтобы заменить Python",
    "To hide source code": "Чтобы скрыть исходный код",
    "Exchanging structured data": "Обмен структурированными данными",
    "Drawing pictures": "Рисование картинок",
    "Compiling Python": "Компиляция Python",
    "Styling web pages": "Оформление веб-страниц",
    "A matching pattern anywhere in the text": "Подходящий шаблон в любой части текста",
    "Only at the final character": "Только в последнем символе",
    "Only Python keywords": "Только ключевые слова Python",
    "A file on disk": "Файл на диске",
    "Setting initial object data": "Задание начальных данных объекта",
    "Deleting every object": "Удаление всех объектов",
    "Importing modules": "Импорт модулей",
    "Starting a loop": "Запуск цикла",
    "The current object": "Текущий объект",
    "The parent file": "Родительский файл",
    "Every class at once": "Все классы одновременно",
    "Python itself": "Сам Python",
    "Reuse behavior from a parent class": "Повторно использовать поведение родительского класса",
    "Delete Python": "Удалить Python",
    "Avoid all methods": "Не использовать методы",
    "Become a list": "Стать списком",
    "A child class provides its own version": "Дочерний класс создаёт свою версию",
    "A method runs twice": "Метод запускается дважды",
    "A variable becomes global": "Переменная становится глобальной",
    "A file is renamed": "Файл переименовывается",
    "Controlling access to object details": "Управление доступом к деталям объекта",
    "Sorting every collection": "Сортировка каждой коллекции",
    "Replacing functions with loops": "Замена функций циклами",
    "Installing packages": "Установка пакетов",
    "It closes the file automatically": "Файл закрывается автоматически",
    "It makes every file public": "Все файлы становятся публичными",
    "It converts files to JSON": "Файлы преобразуются в JSON",
    "It prevents all errors": "Предотвращает все ошибки",
    "No": "Нет",
    "Yes, always": "Да, всегда",
    "Only strings": "Только строки",
    "Only the first item": "Только первый элемент",
    "A trailing comma": "Запятая после элемента",
    "Two values": "Два значения",
    "Square brackets": "Квадратные скобки",
    "The tuple keyword": "Ключевое слово tuple",
    "False only": "Только False",
    "0 only": "Только 0",
    "empty": "empty",
}


def _q(level, text_en, text_ru, correct, wrong, explanation_en="", explanation_ru=""):
    return {
        "difficulty": level,
        "text_en": text_en,
        "text_ru": text_ru,
        "correct": correct,
        "wrong": wrong,
        "explanation_en": explanation_en,
        "explanation_ru": explanation_ru,
    }


PYTHON_TOPICS = [
    {
        "key": "syntax",
        "title_en": "Getting Started and Syntax",
        "title_ru": "Начало работы и синтаксис",
        "description_en": "Running Python, indentation, statements and code blocks.",
        "description_ru": "Запуск Python, отступы, инструкции и блоки кода.",
        "questions": [
            _q("beginner", "Which file extension is normally used for Python code?", "Какое расширение обычно используется для файлов Python?", ".py", [".html", ".css", ".jpg"]),
            _q("intermediate", "What does Python use to mark a block of code?", "Что Python использует для обозначения блока кода?", "Indentation", ["Curly braces only", "Semicolons", "Quotation marks"]),
            _q("advanced", "Which line is valid Python syntax?", "Какая строка содержит правильный синтаксис Python?", "if score > 5:", ["if (score > 5) then", "if score > 5 {}", "if score > 5 do"]),
        ],
    },
    {
        "key": "output_comments",
        "title_en": "Output and Comments",
        "title_ru": "Вывод и комментарии",
        "description_en": "Using print() and writing notes that Python ignores.",
        "description_ru": "Использование print() и комментариев, которые Python не выполняет.",
        "questions": [
            _q("beginner", "Which function prints text?", "Какая функция выводит текст?", "print()", ["input()", "len()", "type()"]),
            _q("intermediate", "Which symbol starts a single-line comment?", "Какой символ начинает однострочный комментарий?", "#", ["//", "<!--", "**"]),
            _q("advanced", "What does print('A', 'B', sep='-') display?", "Что выведет print('A', 'B', sep='-')?", "A-B", ["AB", "A B", "A, B"]),
        ],
    },
    {
        "key": "variables",
        "title_en": "Variables",
        "title_ru": "Переменные",
        "description_en": "Creating, naming, assigning and using variables.",
        "description_ru": "Создание, именование, присваивание и использование переменных.",
        "questions": [
            _q("beginner", "Which line creates a variable named age?", "Какая строка создаёт переменную age?", "age = 10", ["10 = age", "var age = 10", "age == 10"]),
            _q("intermediate", "Which is a valid variable name?", "Какое имя переменной допустимо?", "player_score", ["2score", "player-score", "class"]),
            _q("advanced", "After x, y = 3, 7, what is y?", "После x, y = 3, 7 чему равен y?", "7", ["3", "10", "x"]),
        ],
    },
    {
        "key": "data_types",
        "title_en": "Data Types",
        "title_ru": "Типы данных",
        "description_en": "Strings, numbers, booleans, collections and type().",
        "description_ru": "Строки, числа, логические значения, коллекции и type().",
        "questions": [
            _q("beginner", "Which type stores text?", "Какой тип хранит текст?", "str", ["int", "bool", "float"]),
            _q("intermediate", "What is the type of [1, 2, 3]?", "Какой тип имеет [1, 2, 3]?", "list", ["tuple", "set", "dict"]),
            _q("advanced", "What does type(True) report?", "Что покажет type(True)?", "bool", ["int", "str", "None"]),
        ],
    },
    {
        "key": "numbers_casting",
        "title_en": "Numbers and Casting",
        "title_ru": "Числа и преобразование типов",
        "description_en": "Integers, floats, complex numbers and type conversion.",
        "description_ru": "Целые, дробные, комплексные числа и преобразование типов.",
        "questions": [
            _q("beginner", "What is the type of 3.5?", "Какой тип имеет 3.5?", "float", ["int", "str", "bool"]),
            _q("intermediate", "What does int('12') produce?", "Что вернёт int('12')?", "The integer 12", ["The text '12'", "12.0", "An error"]),
            _q("advanced", "What is int(4.9)?", "Чему равно int(4.9)?", "4", ["5", "4.9", "An error"]),
        ],
    },
    {
        "key": "strings",
        "title_en": "Strings",
        "title_ru": "Строки",
        "description_en": "Indexing, slicing, methods, joining, formatting and escapes.",
        "description_ru": "Индексы, срезы, методы, объединение, форматирование и экранирование.",
        "questions": [
            _q("beginner", "Which value is a string?", "Какое значение является строкой?", "'hello'", ["42", "True", "[1, 2]"]),
            _q("intermediate", "What is 'Python'[0]?", "Чему равно 'Python'[0]?", "P", ["y", "Python", "0"]),
            _q("advanced", "What is 'coding'[1:4]?", "Чему равно 'coding'[1:4]?", "odi", ["cod", "oding", "di"]),
        ],
    },
    {
        "key": "booleans",
        "title_en": "Booleans",
        "title_ru": "Логические значения",
        "description_en": "True, False, comparisons and truthy or falsy values.",
        "description_ru": "True, False, сравнения и истинность значений.",
        "questions": [
            _q("beginner", "Which are Python's boolean values?", "Какие логические значения есть в Python?", "True and False", ["Yes and No", "1 and 2", "On and Off"]),
            _q("intermediate", "What is 8 > 3?", "Чему равно 8 > 3?", "True", ["False", "8", "3"]),
            _q("advanced", "What is bool('')?", "Чему равно bool('')?", "False", ["True", "None", "An error"]),
        ],
    },
    {
        "key": "operators",
        "title_en": "Operators",
        "title_ru": "Операторы",
        "description_en": "Arithmetic, assignment, comparison, logical and membership operators.",
        "description_ru": "Арифметические операторы, присваивание, сравнение, логика и принадлежность.",
        "questions": [
            _q("beginner", "Which operator adds two numbers?", "Какой оператор складывает два числа?", "+", ["-", "*", "=="]),
            _q("intermediate", "What is 11 // 4?", "Чему равно 11 // 4?", "2", ["2.75", "3", "1"]),
            _q("advanced", "What is 2 + 3 * 4?", "Чему равно 2 + 3 * 4?", "14", ["20", "24", "10"]),
        ],
    },
    {
        "key": "lists",
        "title_en": "Lists",
        "title_ru": "Списки",
        "description_en": "Accessing, changing, adding, removing, sorting and copying list items.",
        "description_ru": "Доступ, изменение, добавление, удаление, сортировка и копирование списков.",
        "questions": [
            _q("beginner", "Which brackets create a list?", "Какие скобки создают список?", "[]", ["()", "{}", "<>"]),
            _q("intermediate", "Which method adds one item to the end of a list?", "Какой метод добавляет один элемент в конец списка?", "append()", ["add()", "push()", "join()"]),
            _q("advanced", "What is [x * 2 for x in range(3)]?", "Чему равно [x * 2 for x in range(3)]?", "[0, 2, 4]", ["[2, 4, 6]", "[0, 1, 2]", "[0, 2, 4, 6]"]),
        ],
    },
    {
        "key": "tuples",
        "title_en": "Tuples",
        "title_ru": "Кортежи",
        "description_en": "Ordered immutable collections, packing and unpacking.",
        "description_ru": "Упорядоченные неизменяемые коллекции, упаковка и распаковка.",
        "questions": [
            _q("beginner", "Which brackets usually create a tuple?", "Какие скобки обычно создают кортеж?", "()", ["[]", "{}", "<>"]),
            _q("intermediate", "Can tuple items be changed directly?", "Можно ли напрямую изменить элементы кортежа?", "No", ["Yes, always", "Only strings", "Only the first item"]),
            _q("advanced", "What is needed for a one-item tuple?", "Что необходимо для кортежа из одного элемента?", "A trailing comma", ["Two values", "Square brackets", "The tuple keyword"]),
        ],
    },
    {
        "key": "sets",
        "title_en": "Sets and Frozensets",
        "title_ru": "Множества и frozenset",
        "description_en": "Unique items, set operations and immutable frozensets.",
        "description_ru": "Уникальные элементы, операции множеств и неизменяемый frozenset.",
        "questions": [
            _q("beginner", "What does a set remove automatically?", "Что множество удаляет автоматически?", "Duplicate values", ["All numbers", "All strings", "The first value"]),
            _q("intermediate", "Which method adds an item to a set?", "Какой метод добавляет элемент в множество?", "add()", ["append()", "push()", "insert()"]),
            _q("advanced", "Which operator finds common items in two sets?", "Какой оператор находит общие элементы двух множеств?", "&", ["|", "+", "//"]),
        ],
    },
    {
        "key": "dictionaries",
        "title_en": "Dictionaries",
        "title_ru": "Словари",
        "description_en": "Key-value data, access, updates, loops and nested dictionaries.",
        "description_ru": "Пары ключ-значение, доступ, изменение, циклы и вложенные словари.",
        "questions": [
            _q("beginner", "A dictionary stores data as what?", "В каком виде словарь хранит данные?", "Key-value pairs", ["Only numbers", "Rows and columns", "Unique values only"]),
            _q("intermediate", "How do you read the age in {'age': 12}?", "Как получить age из {'age': 12}?", "data['age']", ["data.age()", "data(0)", "data->age"]),
            _q("advanced", "Which method safely returns a value or a default?", "Какой метод безопасно возвращает значение или значение по умолчанию?", "get()", ["append()", "sort()", "index()"]),
        ],
    },
    {
        "key": "conditions",
        "title_en": "If, Elif and Else",
        "title_ru": "Условия if, elif и else",
        "description_en": "Making decisions, combining conditions and nested if statements.",
        "description_ru": "Принятие решений, объединение условий и вложенные условия.",
        "questions": [
            _q("beginner", "Which keyword begins a condition?", "Какое ключевое слово начинает условие?", "if", ["for", "def", "try"]),
            _q("intermediate", "Which block runs when earlier conditions are false?", "Какой блок выполняется, если предыдущие условия ложны?", "else", ["import", "return", "while"]),
            _q("advanced", "What does pass do inside an empty if block?", "Что делает pass внутри пустого блока if?", "It performs no action", ["It stops Python", "It repeats the block", "It prints pass"]),
        ],
    },
    {
        "key": "match",
        "title_en": "Match",
        "title_ru": "Конструкция match",
        "description_en": "Selecting a case with match and case patterns.",
        "description_ru": "Выбор варианта с помощью match и шаблонов case.",
        "questions": [
            _q("beginner", "Which keyword starts pattern matching?", "Какое слово начинает сопоставление с образцом?", "match", ["switch", "choose", "select"]),
            _q("intermediate", "Which keyword defines one match branch?", "Какое слово задаёт одну ветку match?", "case", ["when", "elif", "branch"]),
            _q("advanced", "Which pattern acts as the default case?", "Какой шаблон работает как вариант по умолчанию?", "_", ["*", "default", "else"]),
        ],
    },
    {
        "key": "while",
        "title_en": "While Loops",
        "title_ru": "Циклы while",
        "description_en": "Repeating while a condition is true, break and continue.",
        "description_ru": "Повторение, пока условие истинно, break и continue.",
        "questions": [
            _q("beginner", "A while loop repeats while what is true?", "Цикл while повторяется, пока истинно что?", "Its condition", ["A file", "A comment", "A function name"]),
            _q("intermediate", "Which keyword exits a loop immediately?", "Какое слово немедленно завершает цикл?", "break", ["continue", "pass", "next"]),
            _q("advanced", "Which keyword skips to the next loop iteration?", "Какое слово переходит к следующей итерации?", "continue", ["break", "return", "stop"]),
        ],
    },
    {
        "key": "for_range",
        "title_en": "For Loops and Range",
        "title_ru": "Циклы for и range",
        "description_en": "Looping over collections and generating number sequences.",
        "description_ru": "Перебор коллекций и создание последовательностей чисел.",
        "questions": [
            _q("beginner", "Which loop is commonly used to visit every list item?", "Какой цикл обычно перебирает все элементы списка?", "for", ["if", "try", "match"]),
            _q("intermediate", "What numbers come from range(3)?", "Какие числа создаёт range(3)?", "0, 1, 2", ["1, 2, 3", "0, 1, 2, 3", "3 only"]),
            _q("advanced", "What numbers come from range(2, 8, 2)?", "Какие числа создаёт range(2, 8, 2)?", "2, 4, 6", ["2, 4, 6, 8", "2, 3, 4, 5, 6, 7", "0, 2, 4, 6"]),
        ],
    },
    {
        "key": "functions",
        "title_en": "Functions",
        "title_ru": "Функции",
        "description_en": "Defining functions, parameters, return values and reusable code.",
        "description_ru": "Создание функций, параметры, возвращаемые значения и повторное использование кода.",
        "questions": [
            _q("beginner", "Which keyword defines a function?", "Какое слово создаёт функцию?", "def", ["func", "make", "return"]),
            _q("intermediate", "Which keyword sends a value back from a function?", "Какое слово возвращает значение из функции?", "return", ["print", "yield", "break"]),
            _q("advanced", "What is a parameter?", "Что такое параметр?", "A name in a function definition", ["The final printed value", "A Python file", "A loop condition"]),
        ],
    },
    {
        "key": "arguments_scope",
        "title_en": "Arguments, *args, **kwargs and Scope",
        "title_ru": "Аргументы, *args, **kwargs и область видимости",
        "description_en": "Flexible arguments and where variables can be accessed.",
        "description_ru": "Гибкие аргументы и доступность переменных.",
        "questions": [
            _q("beginner", "A variable created inside a function is usually what?", "Переменная внутри функции обычно является какой?", "Local", ["Global", "Imported", "Constant"]),
            _q("intermediate", "What does *args collect?", "Что собирает *args?", "Extra positional arguments", ["Only keyword arguments", "Errors", "Modules"]),
            _q("advanced", "What does **kwargs collect?", "Что собирает **kwargs?", "Extra keyword arguments", ["Only numbers", "Loop values", "Return statements"]),
        ],
    },
    {
        "key": "lambda_recursion",
        "title_en": "Lambda and Recursion",
        "title_ru": "Lambda и рекурсия",
        "description_en": "Small anonymous functions and functions that call themselves.",
        "description_ru": "Небольшие анонимные функции и функции, вызывающие сами себя.",
        "questions": [
            _q("beginner", "What creates a small anonymous function?", "Что создаёт небольшую анонимную функцию?", "lambda", ["class", "import", "while"]),
            _q("intermediate", "What is recursion?", "Что такое рекурсия?", "A function calling itself", ["A list sorting itself", "A variable changing type", "A module import"]),
            _q("advanced", "Why does recursion need a base case?", "Зачем рекурсии базовый случай?", "To stop the repeated calls", ["To print every result", "To create a class", "To import math"]),
        ],
    },
    {
        "key": "decorators_generators",
        "title_en": "Decorators and Generators",
        "title_ru": "Декораторы и генераторы",
        "description_en": "Wrapping function behavior and producing values with yield.",
        "description_ru": "Изменение поведения функций и создание значений с yield.",
        "questions": [
            _q("beginner", "Which keyword produces a generator value?", "Какое слово выдаёт значение генератора?", "yield", ["return only", "print", "send"]),
            _q("intermediate", "Which symbol commonly applies a decorator?", "Какой символ обычно применяет декоратор?", "@", ["#", "$", "&"]),
            _q("advanced", "What is a key benefit of generators?", "Какое важное преимущество генераторов?", "They produce values lazily", ["They always sort values", "They replace every class", "They disable loops"]),
        ],
    },
    {
        "key": "arrays_iterators",
        "title_en": "Arrays and Iterators",
        "title_ru": "Массивы и итераторы",
        "description_en": "Array-like lists, iterable objects, iter() and next().",
        "description_ru": "Списки как массивы, итерируемые объекты, iter() и next().",
        "questions": [
            _q("beginner", "Which built-in collection is commonly used as an array in basic Python?", "Какая встроенная коллекция обычно используется как массив в базовом Python?", "list", ["str", "bool", "None"]),
            _q("intermediate", "Which function creates an iterator?", "Какая функция создаёт итератор?", "iter()", ["next()", "range()", "open()"]),
            _q("advanced", "Which function requests the next iterator value?", "Какая функция запрашивает следующее значение итератора?", "next()", ["iter()", "step()", "move()"]),
        ],
    },
    {
        "key": "modules_pip_venv",
        "title_en": "Modules, PIP and Virtual Environments",
        "title_ru": "Модули, PIP и виртуальные окружения",
        "description_en": "Importing code, installing packages and isolating projects.",
        "description_ru": "Импорт кода, установка пакетов и изоляция проектов.",
        "questions": [
            _q("beginner", "Which keyword loads a module?", "Какое слово загружает модуль?", "import", ["include", "load", "using"]),
            _q("intermediate", "What is pip mainly used for?", "Для чего в основном используется pip?", "Installing Python packages", ["Writing comments", "Creating loops", "Drawing windows"]),
            _q("advanced", "Why use a virtual environment?", "Зачем использовать виртуальное окружение?", "To isolate project dependencies", ["To speed up every loop", "To replace Python", "To hide source code"]),
        ],
    },
    {
        "key": "dates_math",
        "title_en": "Dates and Math",
        "title_ru": "Даты и математика",
        "description_en": "Working with datetime, math functions and numeric helpers.",
        "description_ru": "Работа с datetime, математическими функциями и числами.",
        "questions": [
            _q("beginner", "Which module provides many mathematical functions?", "Какой модуль содержит математические функции?", "math", ["json", "randomtext", "files"]),
            _q("intermediate", "What does abs(-7) return?", "Что вернёт abs(-7)?", "7", ["-7", "0", "49"]),
            _q("advanced", "Which datetime method gets the current local date and time?", "Какой метод datetime получает текущие локальные дату и время?", "datetime.now()", ["datetime.stop()", "date.time()", "now.datetime()"]),
        ],
    },
    {
        "key": "json",
        "title_en": "JSON",
        "title_ru": "JSON",
        "description_en": "Converting between JSON text and Python values.",
        "description_ru": "Преобразование между текстом JSON и значениями Python.",
        "questions": [
            _q("beginner", "What is JSON commonly used for?", "Для чего обычно используется JSON?", "Exchanging structured data", ["Drawing pictures", "Compiling Python", "Styling web pages"]),
            _q("intermediate", "Which function reads JSON text into Python?", "Какая функция читает текст JSON в Python?", "json.loads()", ["json.dumps()", "json.open()", "json.reads()"]),
            _q("advanced", "Which function converts a Python value to JSON text?", "Какая функция превращает значение Python в текст JSON?", "json.dumps()", ["json.loads()", "json.parse()", "json.text()"]),
        ],
    },
    {
        "key": "regex",
        "title_en": "Regular Expressions",
        "title_ru": "Регулярные выражения",
        "description_en": "Searching and validating text patterns with re.",
        "description_ru": "Поиск и проверка шаблонов текста с помощью re.",
        "questions": [
            _q("beginner", "Which module supports regular expressions?", "Какой модуль поддерживает регулярные выражения?", "re", ["regexpy", "text", "find"]),
            _q("intermediate", "Which pattern matches a digit?", "Какой шаблон соответствует цифре?", "\\d", ["\\s", "\\w only letters", ".py"]),
            _q("advanced", "What does re.search() look for?", "Что ищет re.search()?", "A matching pattern anywhere in the text", ["Only at the final character", "Only Python keywords", "A file on disk"]),
        ],
    },
    {
        "key": "exceptions",
        "title_en": "Try and Except",
        "title_ru": "Обработка ошибок try и except",
        "description_en": "Catching errors, else, finally and raising exceptions.",
        "description_ru": "Перехват ошибок, else, finally и создание исключений.",
        "questions": [
            _q("beginner", "Which block contains code that may fail?", "Какой блок содержит код, где возможна ошибка?", "try", ["except", "finally", "raise"]),
            _q("intermediate", "Which block handles a matching error?", "Какой блок обрабатывает подходящую ошибку?", "except", ["else", "for", "match"]),
            _q("advanced", "Which block runs whether an error happens or not?", "Какой блок выполняется независимо от ошибки?", "finally", ["except only", "elif", "yield"]),
        ],
    },
    {
        "key": "formatting_none_input",
        "title_en": "Formatting, None and User Input",
        "title_ru": "Форматирование, None и ввод пользователя",
        "description_en": "f-strings, missing values and reading keyboard input.",
        "description_ru": "f-строки, отсутствие значения и ввод с клавиатуры.",
        "questions": [
            _q("beginner", "What does input() return?", "Что возвращает input()?", "A string", ["Always an integer", "A boolean", "Nothing"]),
            _q("intermediate", "Which value means no value is present?", "Какое значение означает отсутствие значения?", "None", ["False only", "0 only", "empty"]),
            _q("advanced", "Which is an f-string?", "Какая строка является f-строкой?", "f'Hi {name}'", ["'Hi {name}'", "format'Hi name'", "f(Hi name)"]),
        ],
    },
    {
        "key": "oop_basics",
        "title_en": "Classes, Objects, __init__ and self",
        "title_ru": "Классы, объекты, __init__ и self",
        "description_en": "Creating classes, instances, properties and methods.",
        "description_ru": "Создание классов, объектов, свойств и методов.",
        "questions": [
            _q("beginner", "Which keyword creates a class?", "Какое слово создаёт класс?", "class", ["object", "new", "def"]),
            _q("intermediate", "What is __init__ commonly used for?", "Для чего обычно используется __init__?", "Setting initial object data", ["Deleting every object", "Importing modules", "Starting a loop"]),
            _q("advanced", "What does self refer to inside an instance method?", "На что указывает self внутри метода объекта?", "The current object", ["The parent file", "Every class at once", "Python itself"]),
        ],
    },
    {
        "key": "oop_design",
        "title_en": "Inheritance, Polymorphism and Encapsulation",
        "title_ru": "Наследование, полиморфизм и инкапсуляция",
        "description_en": "Reusing classes, shared interfaces and protecting object details.",
        "description_ru": "Повторное использование классов, общий интерфейс и защита деталей объекта.",
        "questions": [
            _q("beginner", "What does inheritance let a child class do?", "Что наследование позволяет дочернему классу?", "Reuse behavior from a parent class", ["Delete Python", "Avoid all methods", "Become a list"]),
            _q("intermediate", "What is method overriding?", "Что такое переопределение метода?", "A child class provides its own version", ["A method runs twice", "A variable becomes global", "A file is renamed"]),
            _q("advanced", "What is encapsulation mainly about?", "В чём основная идея инкапсуляции?", "Controlling access to object details", ["Sorting every collection", "Replacing functions with loops", "Installing packages"]),
        ],
    },
    {
        "key": "files",
        "title_en": "File Handling",
        "title_ru": "Работа с файлами",
        "description_en": "Opening, reading, writing, creating and deleting files.",
        "description_ru": "Открытие, чтение, запись, создание и удаление файлов.",
        "questions": [
            _q("beginner", "Which function opens a file?", "Какая функция открывает файл?", "open()", ["file()", "read()", "start()"]),
            _q("intermediate", "Which mode opens a file for reading?", "Какой режим открывает файл для чтения?", "'r'", ["'w'", "'a'", "'x'"]),
            _q("advanced", "Why is with open(...) useful?", "Почему удобно использовать with open(...)?", "It closes the file automatically", ["It makes every file public", "It converts files to JSON", "It prevents all errors"]),
        ],
    },
]
